config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources 'sessions', only: [:new, :create]
  delete 'sessions' => 'sessions#destroy'
  resources 'users', only: [:create, :edit, :update]
  resources 'events'
  resources 'rsvps', only: [:create, :destroy]
  resources 'comments', only: :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :event
  validates :content, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :state
  belongs_to :user
  has_many :rsvps, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :attendees, through: :rsvps, source: :user
  validates :name, :date, :city, :state, presence: true
  validate :event_is_in_the_future

  def event_is_in_the_future
  	if date <= Date.today
  		errors.add(:date, "must be in the future")
  	end
  end
end

app/models/rsvp.rb
class Rsvp < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/state.rb
class State < ApplicationRecord
	has_many :events
	has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :state
  has_many :events
  has_many :rsvps, dependent: :destroy
  has_secure_password

  validates :first_name, :last_name, :email, :city, :state, presence: true
  validates :password, :password_confirmation, presence: true, if: :password_digest_changed?
  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
  validates :email, uniqueness: { case_sensitive: false }, format: { with: EMAIL_REGEX }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
  	User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def require_login
  	redirect_to root if session[:user_id] == nil
  end

  def require_correct_user
  	user = User.find(params[:id])
  	redirect_to edit_user_path(current_user.id) if current_user != user
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	c_params = comment_params
  	c_params['user'] = current_user
  	c_params['event'] = Event.find(comment_params['event'].to_i)
  	@comment = Comment.new( c_params )
  	if @comment.save
  		redirect_to :back
  	else
  		flash[:errors] = @comment.errors.full_messages
  		redirect_to :back
  	end
  end

  private
  	def comment_params
  		params.require(:comment).permit(:content, :event)
  	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  before_action :require_login

  def index
    @user = current_user
    @localEvents = Event.where(state: @user.state)
    @otherEvents = Event.where.not(state: @user.state)
    @rsvp = Rsvp.new
    @event = Event.new
    @states = State.all
  end

  def create
    e_params = event_params
    e_params['user'] = current_user
    e_params['state'] = State.find(event_params['state_id'].to_i)
    e_params['date'] = Date.parse(event_params['date'])
    e_params.delete('state_id')
    puts Date.parse(event_params['date'])
    puts e_params['date']
    puts Date.today
    @event = Event.new( e_params )
    if @event.save
      redirect_to events_path
    else
      flash[:errors] = @event.errors.full_messages
      redirect_to events_path
    end
  end

  def edit
    @event = Event.find(params[:id])
    @states = State.all
  end

  def update
    @event = Event.find(params[:id])
    e_params = event_params
    puts e_params
    e_params['state'] = State.find(event_params[:state_id].to_i)
    e_params['date'] = Date.parse(event_params['date'])
    e_params.delete('state_id')
    if @event.update( e_params )
      redirect_to events_path
    else
      flash[:errors] = @event.errors.full_messages
      redirect_to :back
    end
  end

  def show
    @event = Event.find(params[:id])
    @comment = Comment.new
  end

  def destroy
    Event.find(params[:id]).destroy if Event.find(params[:id]).user == current_user
    redirect_to events_path
  end

  private
    def event_params
      params.require(:event).permit(:name, :date, :city, :state_id)
    end

end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  def create
  	r_params = rsvp_params
  	r_params['user'] = current_user
  	r_params['event'] = Event.find( rsvp_params['event'].to_i )
  	@rsvp = Rsvp.new( r_params )
  	if @rsvp.save
  		redirect_to events_path
  	else
  		flash[:errors]
  		redirect_to events_path
  	end
  end

  def destroy
  	Rsvp.find(params[:id]).destroy if Rsvp.find(params[:id]).user == current_user
  	redirect_to events_path
  end

  private
  	def rsvp_params
  		params.require(:rsvp).permit(:user, :event)
  	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	@user = User.new
  	@states = State.all
  	@session = User.new
  end

  def create
  	@session = User.find_by( email: session_params['email'] )
  	if @session
  		if !@session.authenticate( session_params['password'] )
  			flash[:alert] = "Invalid Password"
  			redirect_to new_session_path
  		else
  			session[:user_id] = @session.id
  			redirect_to events_path
  		end
  	else
  		flash[:alert] = "Invalid Email"
  		redirect_to new_session_path
  	end
  end

  def destroy
    session.clear
    redirect_to new_session_path
  end

  private
  	def session_params
  		params.require(:user).permit(:email, :password)
  	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :require_login, only: [:update, :edit]
	before_action :require_correct_user, only: [:update, :edit]

  def create
  	u_params = user_params
  	u_params['state'] = State.find(user_params['state_id'].to_i)
    u_params.delete('state_id')
  	@user = User.new( u_params )
  	if @user.save
  		session[:user_id] = @user.id
  		redirect_to events_path
  	else
  		flash[:errors] = @user.errors.full_messages
  		redirect_to new_session_path
  	end
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update( user_params )
  		redirect_to events_path
  	else
  		flash[:errors] = @user.errors.full_messages
  		redirect_to :back
  	end
  end

  def edit
  	@user = current_user
  end

  private
  	def user_params
  		params.require(:user).permit(:first_name, :last_name, :email, :city, :state_id, :password, :password_confirmation)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<a href="<%= events_path %>">Events Dashboard</a>
<a href="/sessions" data-method="delete">Logout</a>

<h2>Edit Event</h2>

<% if flash[:errors] %>
	<% flash[:errors].each do |err| %>
		<p><%= err %></p>
	<% end %>
<% end %>

<%= form_for @event do |f| %>
	<p>
		<%= f.label :name, "Name" %>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :date, "Date" %>
		<%= f.date_field :date %>
	</p>
	<p>
		<%= f.label :city, "Location" %>
		<%= f.text_field :city %>
		<%= f.collection_select(:state_id, State.all, :id, :abbv)%>
	</p>
	<p>
		<%= f.submit "Update Event", :disable_with => 'Adding...' %>
	</p>
<% end %>

app/views/events/index.html.erb
<h1>Welcome, <%= @user['first_name'] %></h1>
<a href="<%= edit_user_path(@user['id']) %>">Edit My Profile</a>
<a href="sessions" data-method="delete">Logout</a>

<p>Here are some of the events in your state:</p>
<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Date</th>
			<th>Location</th>
			<th>Host</th>
			<th>Action/Status</th>
		</tr>
	</thead>
	<tbody>
		<% @localEvents.each do |event| %>
			<tr>
				<td><a href="<%= event_path(event.id) %>"><%= event.name %></a></td>
				<td><%= event.date.strftime('%D') %></td>
				<td><%= event.city %></td>
				<td><%= event.user.first_name %></td>
				<td>
					<% if event.user == current_user %>	
						<a href="<%= edit_event_path(event.id) %>">Edit</a>
						<a href="events/<%= event['id'] %>" data-method="delete">Delete</a>
					<% elsif event.attendees.include? current_user %>
						Joined
						<a href="rsvps/<%= Rsvp.where(event: event, user: current_user)[0].id %>" data-method="delete">Cancel</a>
					<% else %>
						<%= form_for @rsvp do |f| %>
							<%= f.hidden_field :event, value: event.id %>
							<%= f.hidden_field :user, value: @user %>
							<%= f.submit :value => "Join" %>
						<% end %>
					<% end %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

<p>Here are some of the events in your state:</p>
<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Date</th>
			<th>Location</th>
			<th>State</th>
			<th>Host</th>
			<th>Action/Status</th>
		</tr>
	</thead>
	<tbody>
		<% @otherEvents.each do |event| %>
			<tr>
				<td><a href="<%= event_path(event.id) %>"><%= event.name %></a></td>
				<td><%= event.date.strftime('%D') %></td>
				<td><%= event.city %></td>
				<td><%= event.state.abbv %></td>
				<td><%= event.user.first_name %></td>
				<td>
					<% if event.user == current_user %>	
						<a href="<%= edit_event_path(event.id) %>">Edit</a>
						<a href="events/<%= event['id'] %>" data-method="delete">Delete</a>
					<% elsif event.attendees.include? current_user %>
						Joined
						<a href="rsvps/<%= Rsvp.where(event: event, user: current_user)[0].id %>" data-method="delete">Cancel</a>
					<% else %>
						<%= form_for @rsvp do |f| %>
							<%= f.hidden_field :event, value: event.id %>
							<%= f.hidden_field :user, value: @user %>
							<%= f.submit :value => "Join" %>
						<% end %>
					<% end %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

<h2>Add Event</h2>

<% if flash[:errors] %>
	<% flash[:errors].each do |err| %>
		<p><%= err %></p>
	<% end %>
<% end %>

<%= form_for @event do |f| %>
	<p>
		<%= f.label :name, "Name" %>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :date, "Date" %>
		<%= f.date_field :date %>
	</p>
	<p>
		<%= f.label :city, "Location" %>
		<%= f.text_field :city %>
		<%= f.collection_select(:state_id, @states, :id, :abbv) %>
	</p>
	<p>
		<%= f.submit "Add Event", :disable_with => 'Adding...' %>
	</p>
<% end %>

app/views/events/show.html.erb
<a href="<%= events_path %>">Events Dashboard</a>
<a href="/sessions" data-method="delete">Logout</a>

<h1><%= @event.name %></h1>
<p>Host: <%= @event.user.first_name %> <%= @event.user.last_name %></p>
<p>Date: <%= @event.date %></p>
<p>Location: <%= @event.city %>, <%= @event.state.abbv %></p>
<p>People who are joining the event: <%= @event.attendees.count %></p>

<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>City</th>
			<th>State</th>
		</tr>
	</thead>
	<tbody>
		<% @event.attendees.each do |user| %>
			<tr>
				<td><%= user.first_name %> <%= user.last_name %></td>
				<td><%= user.city %></td>
				<td><%= user.state.abbv %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<% if flash[:errors] %>
	<% flash[:errors].each do |err| %>
		<p><%= err %></p>
	<% end %>
<% end %>

<%= form_for @comment do |f| %>
	
	<%= f.hidden_field :event, :value => @event.id %>

	<%= f.label :content, "Comment" %>
	<%= f.text_area :content %>

	<%= f.submit :value => "Add Comment" %>

<% end %>

<% @event.comments.each do |c| %>
	<p><%= c.user.first_name %> says: <%= c.content %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyBeltPrep</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Edit Your Profile</h1>
<a href="<%= events_path %>">Events Dashboard</a>
<a href="/sessions" data-method="delete">Logout</a>

<% if flash[:errors] %>
	<% flash[:errors].each do |err| %>
		<p><%= err %></p>
	<% end %>
<% end %>

<%= form_for @user do |f| %>

	<p>
		<%= f.label :first_name, "First Name" %>
		<%= f.text_field :first_name %>
	</p>
	<p>
		<%= f.label :last_name, "Last Name" %>
		<%= f.text_field :last_name %>
	</p>
	<p>
		<%= f.label :email %>
		<%= f.email_field :email %>
	</p>
	<p>
		<%= f.label :city, "Location" %>
		<%= f.text_field :city %>
		<%= f.collection_select(:state_id, State.all, :id, :abbv) %>
	</p>

	<%= f.submit :value => "Update Profile" %>

<% end %>